spring:
 datasource:
  url: jdbc:mysql://127.0.0.1:3306/demeng?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
server:
 port: 8088